export enum BlessingTier {
  SILVER = "SILVER",
  GOLD = "GOLD",
  PRISMATIC = "PRISMATIC"
}

export enum Blessing {
  PEARL = "PEARL",
  CROAGUNKS_AID = "CROAGUNKS_AID",
  BAG_OF_SWEETS = "BAG_OF_SWEETS",
  WOBBUFFETS_SILVER_PRIZE = "WOBBUFFETS_SILVER_PRIZE",
  TREASURE_HUNT_I = "TREASURE_HUNT_I",
  STARTER_PACK = "STARTER_PACK",
  NUGGET = "NUGGET",
  GOLDEN_TICKET = "GOLDEN_TICKET",
  TREASURE_HUNT_II = "TREASURE_HUNT_II",
  GIMMIGHOULS_TREASURE = "GIMMIGHOULS_TREASURE",
  INSTANT_HYPER_ROLL = "INSTANT_HYPER_ROLL",
  CINCCINOS_GIFTS_III = "CINCCINOS_GIFTS_III"
}

// TEMPORARY for testing, revert to [4, 12]
export const BLESSING_SELECTION_STAGES = Array.from(
  { length: 20 },
  (_, index) => index + 1
)

export const BLESSING_OPTIONS_PER_SELECTION = 3

export const BLESSING_REROLLS_PER_OPTION = 1
