export enum BlessingTier {
  SILVER = "SILVER",
  GOLD = "GOLD",
  PRISMATIC = "PRISMATIC"
}

export enum Blessing {
  PEARL = "PEARL",
  CROAGUNKS_AID = "CROAGUNKS_AID",
  BAG_OF_SWEETS = "BAG_OF_SWEETS",
  WOBBUFFETS_SILVER_PRIZE = "WOBBUFFETS_SILVER_PRIZE",
  TREASURE_HUNT_I = "TREASURE_HUNT_I",
  STARTER_PACK = "STARTER_PACK",
  NUGGET = "NUGGET",
  GOLDEN_TICKET = "GOLDEN_TICKET",
  TREASURE_HUNT_II = "TREASURE_HUNT_II",
  GIMMIGHOULS_TREASURE = "GIMMIGHOULS_TREASURE",
  INSTANT_HYPER_ROLL = "INSTANT_HYPER_ROLL",
  CINCCINOS_GIFTS_III = "CINCCINOS_GIFTS_III",
  CINCCINOS_GIFTS_I = "CINCCINOS_GIFTS_I",
  CINCCINOS_GIFTS_II = "CINCCINOS_GIFTS_II",
  RELIC_FRAGMENT = "RELIC_FRAGMENT",
  ITEMFINDER_I = "ITEMFINDER_I",
  ITEMFINDER_II = "ITEMFINDER_II",
  ITEMFINDER_III = "ITEMFINDER_III",
  LEGENDARY_GAMBIT = "LEGENDARY_GAMBIT",
  DEEP_INVESTMENTS = "DEEP_INVESTMENTS",
  BERRY_POUCH = "BERRY_POUCH",
  SCHOOL_BUS = "SCHOOL_BUS",
  BANANA_BUSINESS = "BANANA_BUSINESS",
  SWEET_SUBSCRIPTION = "SWEET_SUBSCRIPTION",
  MUNCHLAX_DELIVERY = "MUNCHLAX_DELIVERY",
  POTION = "POTION",
  POCKET_DAYCARE = "POCKET_DAYCARE",
  TRANSFORM = "TRANSFORM",
  TAXES = "TAXES",
  ROCKY_BEGINNINGS = "ROCKY_BEGINNINGS",
  BABYLESS = "BABYLESS",
  HEATRANS_SONG = "HEATRANS_SONG",
  RAYQUAZAS_SONG = "RAYQUAZAS_SONG",
  MEWS_SONG = "MEWS_SONG",
  GROUDONS_SONG = "GROUDONS_SONG",
  ARTICUNOS_SONG = "ARTICUNOS_SONG",
  GIRATINAS_SONG = "GIRATINAS_SONG",
  KYOGRES_SONG = "KYOGRES_SONG"
}

export enum BlessingTrigger {
  PVE_END = "PVE_END",
  PVP_END = "PVP_END",
  CAROUSEL_END = "CAROUSEL_END"
}

// TEMPORARY for testing, revert to [4, 12]
export const BLESSING_SELECTION_STAGES = Array.from(
  { length: 20 },
  (_, index) => index + 1
)

export const BLESSING_OPTIONS_PER_SELECTION = 3

export const BLESSING_REROLLS_PER_OPTION = 1

export interface ScheduledBlessingGrant {
  stage: number
  blessing: Blessing
  value?: number
}
