import { Rarity } from "./Game"
import { Item, SynergyGivenByItem } from "./Item"
import { Pkm, Unowns } from "./Pokemon"
import { Synergy } from "./Synergy"

export enum BlessingTier {
  SILVER = "SILVER",
  GOLD = "GOLD",
  PRISMATIC = "PRISMATIC"
}

export enum Blessing {
  PEARL = "PEARL",
  CROAGUNKS_AID = "CROAGUNKS_AID",
  BAG_OF_SWEETS = "BAG_OF_SWEETS",
  WOBBUFFETS_SILVER_PRIZE = "WOBBUFFETS_SILVER_PRIZE",
  TREASURE_HUNT_I = "TREASURE_HUNT_I",
  STARTER_PACK = "STARTER_PACK",
  NUGGET = "NUGGET",
  GOLDEN_TICKET = "GOLDEN_TICKET",
  TREASURE_HUNT_II = "TREASURE_HUNT_II",
  GIMMIGHOULS_TREASURE = "GIMMIGHOULS_TREASURE",
  INSTANT_HYPER_ROLL = "INSTANT_HYPER_ROLL",
  CINCCINOS_GIFTS_III = "CINCCINOS_GIFTS_III",
  CINCCINOS_GIFTS_I = "CINCCINOS_GIFTS_I",
  CINCCINOS_GIFTS_II = "CINCCINOS_GIFTS_II",
  RELIC_FRAGMENT = "RELIC_FRAGMENT",
  ITEMFINDER_I = "ITEMFINDER_I",
  ITEMFINDER_II = "ITEMFINDER_II",
  ITEMFINDER_III = "ITEMFINDER_III",
  LEGENDARY_GAMBIT = "LEGENDARY_GAMBIT",
  DEEP_INVESTMENTS = "DEEP_INVESTMENTS",
  BERRY_POUCH = "BERRY_POUCH",
  SCHOOL_BUS = "SCHOOL_BUS",
  BANANA_BUSINESS = "BANANA_BUSINESS",
  SWEET_SUBSCRIPTION = "SWEET_SUBSCRIPTION",
  MUNCHLAX_DELIVERY = "MUNCHLAX_DELIVERY",
  POTION = "POTION",
  POCKET_DAYCARE = "POCKET_DAYCARE",
  TRANSFORM = "TRANSFORM",
  TAXES = "TAXES",
  ROCKY_BEGINNINGS = "ROCKY_BEGINNINGS",
  BABYLESS = "BABYLESS",
  HEATRANS_SONG = "HEATRANS_SONG",
  RAYQUAZAS_SONG = "RAYQUAZAS_SONG",
  MEWS_SONG = "MEWS_SONG",
  GROUDONS_SONG = "GROUDONS_SONG",
  ARTICUNOS_SONG = "ARTICUNOS_SONG",
  GIRATINAS_SONG = "GIRATINAS_SONG",
  KYOGRES_SONG = "KYOGRES_SONG",
  FORECAST = "FORECAST",
  WEATHER_INSTITUTE = "WEATHER_INSTITUTE",
  BEEKEEPING = "BEEKEEPING",
  CURSE_OF_TWO = "CURSE_OF_TWO",
  ARCANE_METALS = "ARCANE_METALS",
  VITAMINS = "VITAMINS",
  DRAGON_FANG = "DRAGON_FANG",
  QUIET_STRENGTH = "QUIET_STRENGTH",
  MISFORTUNE = "MISFORTUNE",
  SYNCHRONISED_SPEED_I = "SYNCHRONISED_SPEED_I",
  SYNCHRONISED_SPEED_II = "SYNCHRONISED_SPEED_II",
  POTENTIAL_ENERGY_I = "POTENTIAL_ENERGY_I",
  POTENTIAL_ENERGY_II = "POTENTIAL_ENERGY_II",
  RIVALRY = "RIVALRY",
  SHINY_SAFEGUARD = "SHINY_SAFEGUARD",
  CONTEMPT = "CONTEMPT",
  MISFITS = "MISFITS",
  GARDENING = "GARDENING",
  DOUBLE_WINDFALL = "DOUBLE_WINDFALL",
  AMAZING_GARDENING = "AMAZING_GARDENING",
  FLYTRAP = "FLYTRAP",
  MEGA_SOL = "MEGA_SOL",
  SPORE_CLOUDS = "SPORE_CLOUDS",
  BLOSSOM_FESTIVAL = "BLOSSOM_FESTIVAL",
  NOT_THE_BEES = "NOT_THE_BEES",
  POLLUTED_SEA = "POLLUTED_SEA",
  TIDAL_SURGE = "TIDAL_SURGE",
  ATLANTEAN_MAGIC = "ATLANTEAN_MAGIC",
  STAR_CROSSED_SEAS = "STAR_CROSSED_SEAS",
  ABNORMALITY = "ABNORMALITY",
  WRAPPED_UP = "WRAPPED_UP",
  BRACE_FOR_IMPACT = "BRACE_FOR_IMPACT",
  FROST_BARRIER = "FROST_BARRIER",
  SECOND_WIND = "SECOND_WIND",
  FIRST_WIND = "FIRST_WIND",
  RESURGENCE = "RESURGENCE",
  ECHO_CHAMBER = "ECHO_CHAMBER",
  LANGUAGE_BARRIER = "LANGUAGE_BARRIER",
  MOVE_TUTOR = "MOVE_TUTOR",
  ZAP = "ZAP",
  SEEING_TRIPLE = "SEEING_TRIPLE",
  SACRIFICE = "SACRIFICE",
  DRAGON_KING = "DRAGON_KING",
  ASCENSION = "ASCENSION",
  SHARE_THE_SPOTLIGHT = "SHARE_THE_SPOTLIGHT",
  SLIPSTREAM = "SLIPSTREAM",
  BIG_PECKS = "BIG_PECKS",
  SHAPELESS_SYNERGIES = "SHAPELESS_SYNERGIES",
  BABY_OPENER = "BABY_OPENER",
  SELECTIVE_GENETICS = "SELECTIVE_GENETICS",
  REPLICATOR = "REPLICATOR",
  FIND_A_LOST_WAND = "FIND_A_LOST_WAND",
  FAST_FOOD_DELIVERY = "FAST_FOOD_DELIVERY",
  CHEFS_GREED = "CHEFS_GREED",
  BERRY_BREAKFAST = "BERRY_BREAKFAST",
  GEM_RUSH = "GEM_RUSH",
  DIGGING_EQUIPMENT = "DIGGING_EQUIPMENT",
  CRYSTAL_MUTATION = "CRYSTAL_MUTATION",
  CRYSTAL_CLUSTERS = "CRYSTAL_CLUSTERS",
  BERSERKER_HORDES = "BERSERKER_HORDES",
  HEX_MANIAC = "HEX_MANIAC",
  ABSOLUTE_DARKNESS = "ABSOLUTE_DARKNESS",
  TOXIC_BURST = "TOXIC_BURST",
  EXHAUSTING_FLAME = "EXHAUSTING_FLAME",
  ETERNAL_RAGE = "ETERNAL_RAGE",
  WILD_SUBSCRIPTION = "WILD_SUBSCRIPTION",
  CHOSEN_ONES = "CHOSEN_ONES",
  ADDITIONAL_RETHINK_I = "ADDITIONAL_RETHINK_I",
  SAFARI_ENCOUNTER = "SAFARI_ENCOUNTER",
  GYARODOS_TRES_QUATRO = "GYARODOS_TRES_QUATRO",
  OLIVE_GARDEN = "OLIVE_GARDEN",
  ORBITAL_STRIKE = "ORBITAL_STRIKE",
  ROOSTING_FLOCK = "ROOSTING_FLOCK",
  WATER_FOUNTAIN = "WATER_FOUNTAIN",
  UNISON = "UNISON",
  BERRY_GROWTH = "BERRY_GROWTH",
  MOLECULAR_CORROSION = "MOLECULAR_CORROSION",
  FAST_DELIVERY = "FAST_DELIVERY",
  DEEP_WOUNDS = "DEEP_WOUNDS",
  FERTILE_SOIL = "FERTILE_SOIL",
  SOUL_BLAZE = "SOUL_BLAZE",
  ARCHEOLOGY = "ARCHEOLOGY",
  RAINBOW_DROPLET = "RAINBOW_DROPLET",
  ADOPTION = "ADOPTION",
  MONSTER_KING = "MONSTER_KING",
  GRUDGE = "GRUDGE",
  TIDAL_GUARDIAN = "TIDAL_GUARDIAN",
  OVERLOAD = "OVERLOAD",
  BULL_LEAPING = "BULL_LEAPING",
  ICY_REFLECTION = "ICY_REFLECTION",
  FESTIVE_PICNIC = "FESTIVE_PICNIC",
  MYSTOGAN = "MYSTOGAN",
  MAGNETOSPHERE = "MAGNETOSPHERE",
  GEM_HARVEST = "GEM_HARVEST",
  FURIOUS_FABRIC = "FURIOUS_FABRIC",
  LIMIT_BREAKER = "LIMIT_BREAKER",
  CHAMPIONS_MASK = "CHAMPIONS_MASK",
  AUTO_CRAFTING = "AUTO_CRAFTING",
  CENTER_STAGE = "CENTER_STAGE",
  HIEROGLYPHS = "HIEROGLYPHS",
  FOGBOUND_LAKE = "FOGBOUND_LAKE",
  BURNING_FORCE = "BURNING_FORCE",
  SPIKY_GUARD = "SPIKY_GUARD",
  DRILL_I = "DRILL_I",
  DRILL_II = "DRILL_II",
  SHATTER_I = "SHATTER_I",
  SHATTER_II = "SHATTER_II",
  SURGE_I = "SURGE_I",
  SURGE_II = "SURGE_II",
  GEAR_SHIELD_I = "GEAR_SHIELD_I",
  GEAR_SHIELD_II = "GEAR_SHIELD_II",
  MAGIC_SHIELD_I = "MAGIC_SHIELD_I",
  MAGIC_SHIELD_II = "MAGIC_SHIELD_II",
  BRUTE_SHIELD_I = "BRUTE_SHIELD_I",
  BRUTE_SHIELD_II = "BRUTE_SHIELD_II",
  STAR_GUARD = "STAR_GUARD",
  MACHINE_RESIDUE = "MACHINE_RESIDUE",
  CALCULATED_OFFENCE = "CALCULATED_OFFENCE",
  ROBIN_GEMS = "ROBIN_GEMS",
  SHELL_ARMOR_BLESSING = "SHELL_ARMOR_BLESSING",
  LEAF_TORNADO = "LEAF_TORNADO",
  MARIACHI_MAYHEM = "MARIACHI_MAYHEM",
  ICEBREAKER = "ICEBREAKER",
  RAMPAGE = "RAMPAGE",
  SOUL_DRAIN = "SOUL_DRAIN",
  FLOWER_QUEEN = "FLOWER_QUEEN",
  FROST_BURST = "FROST_BURST",
  AURORA_BOREALIS = "AURORA_BOREALIS",
  RADIANCE = "RADIANCE",
  PACK_ATTACK = "PACK_ATTACK",
  MORTAR_SHELLS = "MORTAR_SHELLS",
  ICE_SPEAR = "ICE_SPEAR",
  FROST_GEAR = "FROST_GEAR",
  SHUTTLE_BUS = "SHUTTLE_BUS",
  PLUNDER = "PLUNDER",
  EMERALD_ORB = "EMERALD_ORB",
  SAPPHIRE_ORB = "SAPPHIRE_ORB",
  RUBY_ORB = "RUBY_ORB",
  LUCKY_DICE_BLESSING = "LUCKY_DICE_BLESSING",
  WOBBUFFETS_GOLD_PRIZE = "WOBBUFFETS_GOLD_PRIZE",
  HARD_COMMIT = "HARD_COMMIT",
  REGIONAL_TREASURES = "REGIONAL_TREASURES",
  REGIONAL_TREASURES_II = "REGIONAL_TREASURES_II",
  SYNARCH = "SYNARCH",
  FLEXIBILITY = "FLEXIBILITY",
  RAINBOW_HOUR = "RAINBOW_HOUR",
  MANIFESTATION_AP = "MANIFESTATION_AP",
  MANIFESTATION_AD = "MANIFESTATION_AD",
  MIX_AND_MATCH_I = "MIX_AND_MATCH_I",
  MIX_AND_MATCH_II = "MIX_AND_MATCH_II",
  WAITING_GAME = "WAITING_GAME",
  PRISMATIC_REROLL = "PRISMATIC_REROLL",
  LUNCH_MONEY = "LUNCH_MONEY",
  CALCULATED_LOSS = "CALCULATED_LOSS",
  A_NEW_FRIEND = "A_NEW_FRIEND",
  BP_REWARDS = "BP_REWARDS",
  GREEDY_WISH = "GREEDY_WISH",
  CALLED_SHOT = "CALLED_SHOT",
  VAMPIRIC = "VAMPIRIC",
  PROTECT_THE_WEAK = "PROTECT_THE_WEAK",
  STURDY = "STURDY",
  ALL_FOR_ONE = "ALL_FOR_ONE",
  RAINBOW_KEY = "RAINBOW_KEY",
  PLUSHIFY = "PLUSHIFY",
  SUPPORTIVE_SOUL = "SUPPORTIVE_SOUL",
  LANCES_ACE = "LANCES_ACE",
  PANIC_BUTTON = "PANIC_BUTTON",
  HAIL_TO_THE_KING = "HAIL_TO_THE_KING",
  TRASH_TO_TREASURE = "TRASH_TO_TREASURE",
  CHARGING_MY_BUG = "CHARGING_MY_BUG",
  NEUROFORCE = "NEUROFORCE",
  SINNOHS_COOLEST = "SINNOHS_COOLEST",
  AXE_BLAST = "AXE_BLAST",
  SWEET_TREATS = "SWEET_TREATS",
  SNIFFER_DOG = "SNIFFER_DOG",
  JESTER = "JESTER",
  TOXIC_RESONANCE = "TOXIC_RESONANCE",
  GRAND_IGNITION = "GRAND_IGNITION",
  VALOR = "VALOR",
  COLONY = "COLONY",
  SAND_BUDDIES = "SAND_BUDDIES",
  YOU_FORGOT_SOMETHING = "YOU_FORGOT_SOMETHING",
  THINK_FAST = "THINK_FAST",
  WISE_SPENDING = "WISE_SPENDING",
  BIRTHDAY_PRESENT = "BIRTHDAY_PRESENT",
  UP_IS_UP = "UP_IS_UP",
  DROP_RATES = "DROP_RATES",
  MORE_EQUAL_THAN_OTHERS = "MORE_EQUAL_THAN_OTHERS",
  CLIMBING_THE_LADDER = "CLIMBING_THE_LADDER",
  FREE_COUPON = "FREE_COUPON",
  QUICK_CLAW = "QUICK_CLAW",
  COLOUR_CHANGE = "COLOUR_CHANGE",
  AZURE_FLUTE = "AZURE_FLUTE",
  ADDITIONAL_RETHINK_II = "ADDITIONAL_RETHINK_II",
  ALL_FOURS = "ALL_FOURS",
  BEING_OF_KNOWLEDGE = "BEING_OF_KNOWLEDGE",
  HYPER_HYPER_ROLL = "HYPER_HYPER_ROLL",
  BEAUTY_CONTEST = "BEAUTY_CONTEST",
  CURSE_OF_CORAL = "CURSE_OF_CORAL",
  TEMPLE_OF_LANGUAGE = "TEMPLE_OF_LANGUAGE",
  TREASURE_TRAIL = "TREASURE_TRAIL",
  TRAINING_MONTAGE = "TRAINING_MONTAGE",
  IMPENDING_DOOM = "IMPENDING_DOOM",
  SYNCHRONICITY = "SYNCHRONICITY",
  STARTER_CHOICE = "STARTER_CHOICE",
  SINGULARITY_I = "SINGULARITY_I",
  SINGULARITY_II = "SINGULARITY_II",
  QUEST_EVOLVE = "QUEST_EVOLVE",
  QUEST_DESTROY = "QUEST_DESTROY",
  QUEST_LEVEL_UP = "QUEST_LEVEL_UP",
  QUEST_DIVERSIFY = "QUEST_DIVERSIFY",
  QUEST_PROSPER = "QUEST_PROSPER",
  QUEST_INDECISION = "QUEST_INDECISION",
  QUEST_CRIT = "QUEST_CRIT",
  QUEST_ABSORB = "QUEST_ABSORB",
  QUEST_REVIVE = "QUEST_REVIVE",
  QUEST_PILLAGE = "QUEST_PILLAGE",
  QUEST_EVOLVE_II = "QUEST_EVOLVE_II",
  QUEST_REROLL = "QUEST_REROLL",
  QUEST_GROW = "QUEST_GROW",
  QUEST_SHINE = "QUEST_SHINE",
  QUEST_EPIC = "QUEST_EPIC",
  QUEST_EXPAND = "QUEST_EXPAND",
  QUEST_ASCEND = "QUEST_ASCEND",
  CHARGING_UP = "CHARGING_UP",
  BURNING_SHARDS = "BURNING_SHARDS",
  EXPLOIT = "EXPLOIT",
  RIPPLING_EFFECTS = "RIPPLING_EFFECTS",
  LASTING_EFFECTS = "LASTING_EFFECTS",
  PULSE_SHIELD_I = "PULSE_SHIELD_I",
  PULSE_SHIELD_II = "PULSE_SHIELD_II",
  MINIMALIST_I = "MINIMALIST_I",
  MINIMALIST_II = "MINIMALIST_II",
  CRITICAL_RUSH_I = "CRITICAL_RUSH_I",
  CRITICAL_RUSH_II = "CRITICAL_RUSH_II",
  CRITICAL_PATH_I = "CRITICAL_PATH_I",
  CRITICAL_PATH_II = "CRITICAL_PATH_II",
  LONE_WOLF = "LONE_WOLF",
  PARTING_GIFT = "PARTING_GIFT",
  REQUIEM = "REQUIEM",
  GUARD_FORMATION = "GUARD_FORMATION",
  BRAVE_FORMATION = "BRAVE_FORMATION",
  TOUGH_FORMATION = "TOUGH_FORMATION",
  NORMAL_BADGE_BLESSING = "NORMAL_BADGE_BLESSING",
  FLYING_BADGE_BLESSING = "FLYING_BADGE_BLESSING",
  FIELD_BADGE_BLESSING = "FIELD_BADGE_BLESSING",
  DARK_BADGE_BLESSING = "DARK_BADGE_BLESSING",
  GROUND_BADGE_BLESSING = "GROUND_BADGE_BLESSING",
  PSYCHIC_BADGE_BLESSING = "PSYCHIC_BADGE_BLESSING",
  GRASS_BADGE_BLESSING = "GRASS_BADGE_BLESSING",
  BUG_BADGE_BLESSING = "BUG_BADGE_BLESSING",
  WATER_BADGE_BLESSING = "WATER_BADGE_BLESSING",
  AQUATIC_BADGE_BLESSING = "AQUATIC_BADGE_BLESSING",
  POISON_BADGE_BLESSING = "POISON_BADGE_BLESSING",
  FAIRY_BADGE_BLESSING = "FAIRY_BADGE_BLESSING",
  FIGHTING_BADGE_BLESSING = "FIGHTING_BADGE_BLESSING",
  FIRE_BADGE_BLESSING = "FIRE_BADGE_BLESSING",
  GHOST_BADGE_BLESSING = "GHOST_BADGE_BLESSING",
  ROCK_BADGE_BLESSING = "ROCK_BADGE_BLESSING",
  MONSTER_BADGE_BLESSING = "MONSTER_BADGE_BLESSING",
  AMORPHOUS_BADGE_BLESSING = "AMORPHOUS_BADGE_BLESSING",
  WILD_BADGE_BLESSING = "WILD_BADGE_BLESSING",
  SOUND_BADGE_BLESSING = "SOUND_BADGE_BLESSING",
  FLORA_BADGE_BLESSING = "FLORA_BADGE_BLESSING",
  STEEL_BADGE_BLESSING = "STEEL_BADGE_BLESSING",
  ELECTRIC_BADGE_BLESSING = "ELECTRIC_BADGE_BLESSING",
  ICE_BADGE_BLESSING = "ICE_BADGE_BLESSING",
  HUMAN_BADGE_BLESSING = "HUMAN_BADGE_BLESSING",
  DRAGON_BADGE_BLESSING = "DRAGON_BADGE_BLESSING",
  LIGHT_BADGE_BLESSING = "LIGHT_BADGE_BLESSING",
  GOURMET_BADGE_BLESSING = "GOURMET_BADGE_BLESSING",
  FOSSIL_BADGE_BLESSING = "FOSSIL_BADGE_BLESSING",
  ARTIFICIAL_BADGE_BLESSING = "ARTIFICIAL_BADGE_BLESSING",
  NORMAL_CREST_BLESSING = "NORMAL_CREST_BLESSING",
  FLYING_CREST_BLESSING = "FLYING_CREST_BLESSING",
  FIELD_CREST_BLESSING = "FIELD_CREST_BLESSING",
  DARK_CREST_BLESSING = "DARK_CREST_BLESSING",
  GROUND_CREST_BLESSING = "GROUND_CREST_BLESSING",
  PSYCHIC_CREST_BLESSING = "PSYCHIC_CREST_BLESSING",
  GRASS_CREST_BLESSING = "GRASS_CREST_BLESSING",
  BUG_CREST_BLESSING = "BUG_CREST_BLESSING",
  WATER_CREST_BLESSING = "WATER_CREST_BLESSING",
  AQUATIC_CREST_BLESSING = "AQUATIC_CREST_BLESSING",
  POISON_CREST_BLESSING = "POISON_CREST_BLESSING",
  FAIRY_CREST_BLESSING = "FAIRY_CREST_BLESSING",
  FIGHTING_CREST_BLESSING = "FIGHTING_CREST_BLESSING",
  FIRE_CREST_BLESSING = "FIRE_CREST_BLESSING",
  GHOST_CREST_BLESSING = "GHOST_CREST_BLESSING",
  ROCK_CREST_BLESSING = "ROCK_CREST_BLESSING",
  MONSTER_CREST_BLESSING = "MONSTER_CREST_BLESSING",
  AMORPHOUS_CREST_BLESSING = "AMORPHOUS_CREST_BLESSING",
  WILD_CREST_BLESSING = "WILD_CREST_BLESSING",
  SOUND_CREST_BLESSING = "SOUND_CREST_BLESSING",
  FLORA_CREST_BLESSING = "FLORA_CREST_BLESSING",
  STEEL_CREST_BLESSING = "STEEL_CREST_BLESSING",
  ELECTRIC_CREST_BLESSING = "ELECTRIC_CREST_BLESSING",
  ICE_CREST_BLESSING = "ICE_CREST_BLESSING",
  HUMAN_CREST_BLESSING = "HUMAN_CREST_BLESSING",
  DRAGON_CREST_BLESSING = "DRAGON_CREST_BLESSING",
  LIGHT_CREST_BLESSING = "LIGHT_CREST_BLESSING",
  GOURMET_CREST_BLESSING = "GOURMET_CREST_BLESSING",
  FOSSIL_CREST_BLESSING = "FOSSIL_CREST_BLESSING",
  ARTIFICIAL_CREST_BLESSING = "ARTIFICIAL_CREST_BLESSING",
  NORMAL_CROWN_BLESSING = "NORMAL_CROWN_BLESSING",
  FLYING_CROWN_BLESSING = "FLYING_CROWN_BLESSING",
  FIELD_CROWN_BLESSING = "FIELD_CROWN_BLESSING",
  DARK_CROWN_BLESSING = "DARK_CROWN_BLESSING",
  GROUND_CROWN_BLESSING = "GROUND_CROWN_BLESSING",
  PSYCHIC_CROWN_BLESSING = "PSYCHIC_CROWN_BLESSING",
  GRASS_CROWN_BLESSING = "GRASS_CROWN_BLESSING",
  BUG_CROWN_BLESSING = "BUG_CROWN_BLESSING",
  WATER_CROWN_BLESSING = "WATER_CROWN_BLESSING",
  AQUATIC_CROWN_BLESSING = "AQUATIC_CROWN_BLESSING",
  POISON_CROWN_BLESSING = "POISON_CROWN_BLESSING",
  FAIRY_CROWN_BLESSING = "FAIRY_CROWN_BLESSING",
  FIGHTING_CROWN_BLESSING = "FIGHTING_CROWN_BLESSING",
  FIRE_CROWN_BLESSING = "FIRE_CROWN_BLESSING",
  GHOST_CROWN_BLESSING = "GHOST_CROWN_BLESSING",
  ROCK_CROWN_BLESSING = "ROCK_CROWN_BLESSING",
  MONSTER_CROWN_BLESSING = "MONSTER_CROWN_BLESSING",
  AMORPHOUS_CROWN_BLESSING = "AMORPHOUS_CROWN_BLESSING",
  WILD_CROWN_BLESSING = "WILD_CROWN_BLESSING",
  SOUND_CROWN_BLESSING = "SOUND_CROWN_BLESSING",
  FLORA_CROWN_BLESSING = "FLORA_CROWN_BLESSING",
  STEEL_CROWN_BLESSING = "STEEL_CROWN_BLESSING",
  ELECTRIC_CROWN_BLESSING = "ELECTRIC_CROWN_BLESSING",
  ICE_CROWN_BLESSING = "ICE_CROWN_BLESSING",
  HUMAN_CROWN_BLESSING = "HUMAN_CROWN_BLESSING",
  DRAGON_CROWN_BLESSING = "DRAGON_CROWN_BLESSING",
  LIGHT_CROWN_BLESSING = "LIGHT_CROWN_BLESSING",
  GOURMET_CROWN_BLESSING = "GOURMET_CROWN_BLESSING",
  FOSSIL_CROWN_BLESSING = "FOSSIL_CROWN_BLESSING",
  ARTIFICIAL_CROWN_BLESSING = "ARTIFICIAL_CROWN_BLESSING",
  SHOW_OFF = "SHOW_OFF"
}

export enum BlessingTrigger {
  PVE_END = "PVE_END",
  PVP_END = "PVP_END",
  CAROUSEL_END = "CAROUSEL_END"
}

export const BLESSING_SELECTION_STAGES = [4, 12]

export const BLESSING_OPTIONS_PER_SELECTION = 3

export const BLESSING_REROLLS_PER_OPTION = 1

export const VITAMINS_ATTACK = 2
export const VITAMINS_ABILITY_POWER = 10
export const VITAMINS_SPEED = 10
export const DRAGON_FANG_ABILITY_POWER_PER_STAR = 2
export const QUIET_STRENGTH_LOW_LIFE_THRESHOLD = 25
export const RIVALRY_ATTACK_ON_OWN_SIDE = 1
export const RIVALRY_MAX_HP_ON_ENEMY_SIDE = 5
export const SHINY_SAFEGUARD_HP_THRESHOLD = 0.5
export const SHINY_SAFEGUARD_PROTECT_DURATION = 1500
export const CONTEMPT_DAMAGE_MULTIPLIER = 1.5
export const POTENTIAL_ENERGY_SHIELD = { I: 25, II: 40 }
export const POTENTIAL_ENERGY_SPEED = { I: 5, II: 10 }
export const MISFITS_MAX_HP = 40
export const MISFITS_ABILITY_POWER = 40
export const MISFITS_ATTACK = 4
export const MISFITS_DEFENSE = 4
export const MISFITS_SPECIAL_DEFENSE = 4
export const BLOSSOM_FESTIVAL_MULCH_MULTIPLIER = 2
export const BLOSSOM_FESTIVAL_CASTS_PER_RANGE_GAIN = 3
export const NOT_THE_BEES_MAX_COMBEES = 16
export const SPORE_CLOUDS_INTERVAL = 3000
export const SPORE_CLOUDS_STATUS_DURATION = 3000
export const MEGA_SOL_AURA_RADIUS = 2
export const BRACE_FOR_IMPACT_MAX_HP_RATIO = 0.5
export const FROST_BARRIER_HP_THRESHOLD = 0.5
export const FROST_BARRIER_DEFENSE = 15
export const FROST_BARRIER_SPEED = 15
export const FROST_BARRIER_CHECK_INTERVAL = 500
export const SECOND_WIND_RESURRECTION_INTERVAL = 10000
export const FIRST_WIND_HEAL_DELAY = 10000
export const FIRST_WIND_HEAL_RATIO = 0.4
export const YOU_FORGOT_SOMETHING_DELAY = 8000
export const VAMPIRIC_HEAL_RATIO = 0.2
export const PROTECT_THE_WEAK_MAX_HP = 20
export const PROTECT_THE_WEAK_SPEED = 7
export const STURDY_MAX_HP = 30
export const STURDY_DEFENSE = 4
export const STURDY_SPECIAL_DEFENSE = 4
export const ALL_FOR_ONE_MAX_HP_RATIO = 0.6
export const RESURGENCE_SPEED = 25
export const RESURGENCE_LEGENDARY_SPEED = 35
export const ECHO_CHAMBER_PP_TO_LEADER = 3
export const ECHO_CHAMBER_PP_TO_ALLIES = 6
export const LANGUAGE_BARRIER_SHIELD = 15
export const LANGUAGE_BARRIER_UNOWNS_GRANTED = 2
export const MOVE_TUTOR_MAX_PP = 80
export const ZAP_CHAIN_DAMAGE_RATIO = 0.5
// on top of the clone the BUG synergy already makes, for three copies in total
export const BUG_CLONE_TRIPLE = 1
export const DRAGON_KING_SHIELD_PER_STAR = 5
export const DRAGON_KING_SPEED_PER_STAR = 1
export const DRAGON_KING_ABILITY_POWER_PER_STAR = 1
export const ASCENSION_BREAK_FREE_CHECK_INTERVAL = 250
export const SACRIFICE_DELAY = 300
/* enough to punch through any shield and survive damage reduction: dealing the
   ally's exact hp left it alive whenever it held a shield or took a reduction */
export const SACRIFICE_EXECUTE_DAMAGE = 9999
export const BABY_OPENER_BABIES_GRANTED = 3
export const BABY_OPENER_MAX_COST = 2
export const BABY_OPENER_LIFE_PER_EGG = 2
export const SELECTIVE_GENETICS_BABIES_GRANTED = 3
export const SELECTIVE_GENETICS_MAX_COST = 4
export const SELECTIVE_GENETICS_SHINY_ITEM_OPTIONS = 3
export const SELECTIVE_GENETICS_GOLDEN_EGG_CHANCE = 0.05
export const FAST_FOOD_DELIVERY_ROUNDS_BEFORE_ROTTING = 1
export const CHEFS_GREED_DISHES = 2
export const CHEFS_GREED_DISHES_WITH_BELT = 3
export const GEM_RUSH_EXTRA_GEMS = 1
export const CRYSTAL_CLUSTERS_SIMULTANEOUS = 2
export const CRYSTAL_CLUSTERS_ROCKS_GRANTED = 2
export const BERSERKER_HORDES_SHOP_INTERVAL = 10
export const SHARE_THE_SPOTLIGHT_RATIO = 0.5
export const SLIPSTREAM_SPEED = 5
export const SHAPELESS_SYNERGIES_MIN_ACTIVE = 3
export const SHAPELESS_SYNERGIES_SPEED_RATIO = 1
export const SHAPELESS_SYNERGIES_HP_RATIO = 0.5
export const POLLUTED_SEA_POISON_DURATION = 3000
export const TIDAL_SURGE_ITEMS_REQUIRED = 2
export const STAR_CROSSED_SEAS_MAX_HP = 50
export const STAR_CROSSED_SEAS_ABILITY_POWER = 25
export const MOLECULAR_CORROSION_DAMAGE_MULTIPLIER = 1.4
export const RAINBOW_DROPLET_SYNERGIES_REQUIRED = 7
export const MONSTER_KING_BEAM_INTERVAL = 8000
export const ADOPTION_STARTERS: Pkm[] = [Pkm.AZURILL, Pkm.PICHU, Pkm.IGGLYBUFF]
export const ADOPTION_FALLBACK = Pkm.HAPPINY
export const ARCHEOLOGY_TWO_STAR_CHANCE = 0.1
export const ARCHEOLOGY_RARITY_WEIGHTS = {
  [Rarity.UNCOMMON]: 60,
  [Rarity.RARE]: 30,
  [Rarity.EPIC]: 10
}
/* one animation beat, so a dasher casting a dash does not overlap itself, then
   re-checked until the unit has stopped moving: dash travel time depends on the
   distance covered, so no fixed delay can cover it */
export const BULL_LEAPING_FOLLOW_UP_DELAY = 500
export const FESTIVE_PICNIC_MAX_HP_ON_OVERWRITE = 5
// additive, applied before luck scales it in chance()
export const MYSTOGAN_PROC_CHANCE_BONUS = 0.05

// long enough for the field animation to play out and settle between flips
/* FURIOUS_FABRIC: every SILK_SCARF recipe mapped to a synergy that overlaps
   well with NORMAL. Kept out of SynergyGivenByItem so the items only grant a
   synergy while the blessing is held */
export const FURIOUS_FABRIC_SYNERGY_BY_SCARF: { [item in Item]?: Synergy } = {
  [Item.BIG_EATER_BELT]: Synergy.GOURMET,
  [Item.EFFICIENT_BANDANNA]: Synergy.SOUND,
  [Item.COVER_BAND]: Synergy.GROUND,
  [Item.TWIST_BAND]: Synergy.PSYCHIC,
  [Item.EXPLOSIVE_BAND]: Synergy.WILD,
  [Item.MACH_RIBBON]: Synergy.FIELD,
  [Item.BLACK_BELT]: Synergy.FIGHTING,
  [Item.LUCKY_RIBBON]: Synergy.FAIRY,
  [Item.TIGHT_BELT]: Synergy.BUG,
  [Item.FRIEND_BOW]: Synergy.GRASS,
  [Item.NULLIFY_BANDANNA]: Synergy.FLYING
}

/* the one place that answers "which synergies does this item give its holder",
   used both when equipping and when removing. An item may give two: its own,
   plus the one FURIOUS_FABRIC adds on top */
export function getSynergiesGivenByItem(
  item: Item,
  blessings?: Blessing[]
): Synergy[] {
  const synergies: Synergy[] = []
  const innate = SynergyGivenByItem[item]
  if (innate) synergies.push(innate)
  if (blessings?.includes(Blessing.FURIOUS_FABRIC)) {
    const fromFabric = FURIOUS_FABRIC_SYNERGY_BY_SCARF[item]
    if (fromFabric && fromFabric !== innate) synergies.push(fromFabric)
  }
  return synergies
}

export const UNISON_METER_DAMAGE = 1000
export const UNISON_TRIGGERED_PROGRESS_OFFSET = UNISON_METER_DAMAGE + 1
export const UNISON_FINISHED_PROGRESS = -1
export const UNISON_CHECK_INTERVAL = 500
export const UNISON_STRIKE_ATTACK_RATIO = 1
export const UNISON_NOVA_DELAY = 600
export const UNISON_STRIKE_DELAY = 1300
export const UNISON_STARFALL_WARNING = 250
export const LIMIT_BREAKER_REROLLS_PER_GOLD = 4
export const GEM_HARVEST_CHARGE_REDUCTION = 1
export const GEM_HARVEST_ATTACK_PER_GEM = 3
export const GEM_HARVEST_ABILITY_POWER_PER_GEM = 10
// long enough for the field animation to play out and settle between flips
export const MAGNETOSPHERE_PULSE_INTERVAL = 8000
// the field flips polarity every pulse, so nothing is ever pulled and pushed at once
/* the rings need time to close before the enemies land, or they arrive before
   the animation's peak. Repelling needs none: its blast leaves immediately */
export const MAGNETOSPHERE_ATTRACT_MOVE_DELAY = 700
// long enough that hauling enemies into your own formation is worth the exposure
export const MAGNETOSPHERE_ATTRACT_PARALYSIS_DURATION = 8000
export const MAGNETOSPHERE_REPEL_LOCK_DURATION = 2000
export const ICY_REFLECTION_TRIGGER_MAX_HP_RATIO = 0.25
// deferred out of the damage resolution it is triggered from
export const ICY_REFLECTION_CAST_DELAY = 250
export const BULL_LEAPING_ARRIVAL_CHECK_INTERVAL = 250
export const BULL_LEAPING_ARRIVAL_MAX_CHECKS = 12
export const OVERLOAD_CAST_INTERVAL = 8000
export const OVERLOAD_FIRST_CAST_DELAY = 500
export const TIDAL_GUARDIAN_WHIRLPOOL_TARGETS = 3
export const FOGBOUND_LAKE_FIREFLIES: Pkm[] = [Pkm.VOLBEAT, Pkm.ILLUMISE]
export const GRUDGE_CURSE_CHANCE = 0.3
export const GRUDGE_CURSE_DURATION = 8000
export const GRUDGE_CURSE_DURATION_REDUCTION_PER_SUBSTITUTE = 1000
export const GRUDGE_SUBSTITUTE_SELL_COST = 4

/* Grudge substitutes are the only manifestation-locked Substitutes, so no
   dedicated schema field is needed to tell them apart */
export function isGrudgeSubstitute(pokemon: {
  name: Pkm
  manifestationLocked?: boolean
}): boolean {
  return pokemon.name === Pkm.SUBSTITUTE && pokemon.manifestationLocked === true
}

/* every CURSE the Grudge owner inflicts is shortened by 1 second per Substitute
   planted on the cursed player's bench, whatever the source of the curse */
export function applyGrudgeCurseReduction(
  duration: number,
  cursedPlayerBoard: { name: Pkm; manifestationLocked?: boolean }[]
): number {
  const substitutesPlanted = cursedPlayerBoard.filter(isGrudgeSubstitute).length
  return Math.max(
    1000,
    duration -
      substitutesPlanted * GRUDGE_CURSE_DURATION_REDUCTION_PER_SUBSTITUTE
  )
}

export const SOUL_BLAZE_SHIELD = 50
export const SOUL_BLAZE_SPEED = 20
export const SOUL_BLAZE_LIFE_HEAL_ON_KO = 1
export const FERTILE_SOIL_DIG_PERMANENT_HP = 5
export const FERTILE_SOIL_HOLE_MAX_HP_RATIO = 0.2
export const FERTILE_SOIL_ABSORB_ROUNDS = 5
export const DEEP_WOUNDS_ARMOR_BREAK_DURATION = 5000
export const DEEP_WOUNDS_DEFENSE_LOSS = 1
export const DEEP_WOUNDS_DEFENSE_LOSS_CHANCE = 0.3
export const FAST_DELIVERY_LUCK_PER_SEED = 5
export const FAST_DELIVERY_RETURN_DELAY = 1
export const BERRY_GROWTH_PERMANENT_HP = 10
export const BERRY_GROWTH_GOLDEN_PERMANENT_HP = 15
export const BERRY_GROWTH_GOLDEN_BERRIES_GRANTED = 2
export const BERRY_GROWTH_GOLDEN_BERRIES_STAGE = 12
export const HEX_MANIAC_STATUS_DURATION = 30000
export const ABSOLUTE_DARKNESS_BLIND_CHANCE = 0.05
export const ABSOLUTE_DARKNESS_BLIND_DURATION = 3000
export const EXHAUSTING_FLAME_DAMAGE_MULTIPLIER = 0.8
export const ETERNAL_RAGE_DURATION_PER_STAR = 1000
export const ORBITAL_STRIKE_RANGE_BONUS = 2
export const SHELL_ARMOR_SPE_DEF_BY_STARS = [1, 3, 6]

export const WOBBUFFETS_GOLD_PRIZE_RECYCLE_TICKETS = 2
export const HARD_COMMIT_STAGES = [10, 20]
export const SYNARCH_GEMS_PER_UNIQUE = 3
export const FLEXIBILITY_FOSSIL_STONES = 3
export const FLEXIBILITY_COMPONENTS = 3
export const FLEXIBILITY_HP_PER_SYNERGY_ITEM = 12
export const RAINBOW_HOUR_FOSSIL_STONES = 2
export const RAINBOW_HOUR_EEVEELUTIONS_TARGET = 7
export const RAINBOW_HOUR_GOLD_REWARD = 77
export const MANIFESTATION_UNLOCK_STAGE = 20
export const MIX_AND_MATCH_I_UNIQUES = 3
export const MIX_AND_MATCH_I_FIELD_CAP = 2
export const MIX_AND_MATCH_II_UNIQUES = 4
export const MIX_AND_MATCH_II_FIELD_CAP = 3

export const WAITING_GAME_FREE_ROLLS = 1
export const WAITING_GAME_FREE_ROLLS_WITHOUT_REROLLING = 2
export const PRISMATIC_REROLL_CHANCE = 0.25
export const PRISMATIC_REROLL_FREE_ROLLS = 2
export const LUNCH_MONEY_DAMAGE_REQUIRED = 8
export const LUNCH_MONEY_GOLD = 2
export const CALCULATED_LOSS_GOLD = 2
export const BP_REWARDS_COMPONENTS = 2
export const BP_REWARDS_RECURRING_COMPONENTS = 1
export const BP_REWARDS_ROUND_INTERVAL = 5
export const LANCES_ACE_DELAY = 3
export const HAIL_TO_THE_KING_MAX_HP = 100
export const HAIL_TO_THE_KING_ATTACK = 10
export const HAIL_TO_THE_KING_DEFENSE = 10
export const HAIL_TO_THE_KING_SPECIAL_DEFENSE = 10
export const HAIL_TO_THE_KING_SPEED = 10
export const HAIL_TO_THE_KING_CURSE_DELAY = 1000
export const TRASH_TO_TREASURE_ROUNDS_BY_STAR = [5, 3, 1] as const
export const TRASH_TO_TREASURE_TRASH_GRANTED_MIN = 1
export const TRASH_TO_TREASURE_TRASH_GRANTED_MAX = 3
export const GREEDY_WISH_PRISMATIC_GOLD = 10
export const CALLED_SHOT_GOLD = 4
export const CALLED_SHOT_STREAK = 4
export const WISE_SPENDING_EXP_PER_REROLL = 1
export const BIRTHDAY_PRESENT_GOLD = 1
export const UP_IS_UP_GOLD = 1
export const UP_IS_UP_LIFE = 1
export const DROP_RATES_CHANCE = 0.4
export const MORE_EQUAL_THAN_OTHERS_GOLD = 10
export const MORE_EQUAL_THAN_OTHERS_GOLD_FOR_OTHERS = 5
export const CLIMBING_THE_LADDER_MIN_LEVEL = 4
export const CLIMBING_THE_LADDER_MAX_LEVEL = 10
export const CLIMBING_THE_LADDER_EXP_DISCOUNT = 4
/* the immediate level up lands the player on 4, so the discount starts there:
   10/22/34/52/72/72 becomes 6/18/30/48/68/68 */
export const CLIMBING_THE_LADDER_DISCOUNT_FROM_LEVEL = 4
export const FREE_COUPON_GUARANTEED_SHOP_STAGE = 22

export const SOUL_DRAIN_HEAL = 20
export const SOUL_DRAIN_FRAGMENTS_ON_KILL = 2
export const FLOWER_QUEEN_MAX_PP_REDUCTION = 4
export const FLOWER_QUEEN_MIN_MAX_PP = 10

export const LEAF_TORNADO_BOUNCES = 2
export const LEAF_TORNADO_DAMAGE_RATIO = 0.5
export const MARIACHI_MAYHEM_CONFUSION_DURATION = 2000
export const RAMPAGE_DURATION_EXTENSION = 2000
export const RAMPAGE_CHANNEL_THRESHOLD = 5000
export const RAMPAGE_DAMAGE_MULTIPLIER = 2

export const FROST_BURST_SPLASH_RATIO = 0.5
export const FROST_BURST_EXECUTE_CHANCE_RATIO = 0.5
export const AURORA_BOREALIS_DAMAGE_REDUCTION = 0.1
export const AURORA_BOREALIS_DAMAGE_REDUCTION_IN_SNOW_OR_NIGHT = 0.15
export const AURORA_BOREALIS_REDUCTION_PER_ACTIVE_SYNERGY = 0.01
export const PACK_ATTACK_HOUNDOOM_CHANCE = 0.2

export const MORTAR_SHELLS_RANGE_BONUS = 3
export const MORTAR_SHELLS_ATTACK_RATIO = 1
export const MORTAR_SHELLS_SPEED_RATIO = 0.5
export const ICE_SPEAR_PP_REFUND_ON_KILL = 20
export const FROST_GEAR_RANGE_BONUS = 2
export const FROST_GEAR_MAX_PP = 70
export const FROST_GEAR_HP_COST_RATIO = 0.1
export const SHUTTLE_BUS_MAX_PP = 110
export const PLUNDER_GOLD_MULTIPLIER = 2

export const JESTER_SUBSTITUTE_MAX_PP = 80
export const JESTER_SUBSTITUTE_MAX_STARS = 4
export const TOXIC_RESONANCE_BEAT_INTERVAL = 3000
export const TOXIC_RESONANCE_HARMONIC_BEAT = 4
export const TOXIC_RESONANCE_POISON_DURATION = 3000
export const TOXIC_RESONANCE_ALLY_PP = 5
export const TOXIC_RESONANCE_HARMONIC_ALLY_PP = 30
export const GRAND_IGNITION_TRUE_DAMAGE_RATIO = 0.1
export const GRAND_IGNITION_MAX_HP_BURNED_RATIO = 0.1
export const GRAND_IGNITION_EMBER_DAMAGE_RATIO = 0.05
export const GRAND_IGNITION_TICK_INTERVAL = 1000
export const GRAND_IGNITION_TORCH_TRAVEL_DELAY = 750
export const VALOR_ATTACK_PER_STAR = 1
export const VALOR_SHIELD_PER_STAR = 10
export const COLONY_SPEWPA_HATCH_TIME = 2

export const EMERALD_ORB_HEAL_RANGE = 2
export const BURNING_FORCE_ATTACK_RATIO = 0.5
export const COMBAT_BLESSING_TRIGGER_HP_RATIO = 0.5
export const COMBAT_BLESSING_DURATION = { I: 8000, II: 12000 }
export const DRILL_ATTACK_RATIO = 0.5
export const SHATTER_DEFENSE_RATIO = 0.5
export const SURGE_SPEED_RATIO = 0.25
export const GEAR_SHIELD_PER_ITEM = { I: 20, II: 30 }
export const MAGIC_SHIELD_ALLY_AP = 30
export const BRUTE_SHIELD_ATTACK_RATIO = 3
export const BRUTE_SHIELD_ALLY_ATTACK = 3
export const STAR_GUARD_DEFENSE_PER_STAR = 1
export const MACHINE_RESIDUE_SHIELD = 20
export const SAPPHIRE_ORB_BOUNCES = 3
export const SAPPHIRE_ORB_ARMOR_BREAK_DURATION = 3000
export const RUBY_ORB_TRUE_DAMAGE_VS_BURN = 0.5
export const LUCKY_DICE_BOUNCE_DAMAGE_RATIO = 0.75

/* blessings that trade away all movement on one future portal carousel for a
   guaranteed pick in the propositions that carousel hands out */
export const BLESSING_CAROUSEL_LOCK: {
  [blessing in Blessing]?: { stage: number; guaranteedPick: Pkm }
} = {
  [Blessing.COLOUR_CHANGE]: { stage: 10, guaranteedPick: Pkm.KECLEON },
  [Blessing.AZURE_FLUTE]: { stage: 20, guaranteedPick: Pkm.ARCEUS }
}

/* the avatar timer is synced and rendered as a countdown, so the lock is a long
   finite delay rather than Infinity */
export const CAROUSEL_LOCK_RETENTION_DELAY = 60000

export const QUICK_CLAW_COMPENSATION_STAGE = 12

// extra picking-phase time on a blessing selection stage, in ms
export const BLESSING_SELECTION_EXTRA_TIME = 30000

export const QUEST_INDECISION_SYNERGIES_TARGET = 3
export const QUEST_CRIT_POWER_TARGET = 4
export const QUEST_ABSORB_DAMAGE_BLOCKED_TARGET = 1300
export const QUEST_REVIVE_TARGET = 20
export const QUEST_PILLAGE_GOLD_TARGET = 30
export const QUEST_PILLAGE_CRIT_PER_GOLD = 0.5
export const QUEST_EVOLVE_II_TARGET = 16

/* quests whose questProgress counter is shown on the Effects tab icon.
   `decimals` is for the ones tracking a best-in-a-fight record rather than a
   running tally, where the value is fractional. */
export const BLESSING_QUEST_TARGETS: {
  [blessing in Blessing]?: { target: number; decimals?: number }
} = {
  [Blessing.QUEST_EVOLVE_II]: { target: QUEST_EVOLVE_II_TARGET },
  [Blessing.QUEST_REVIVE]: { target: QUEST_REVIVE_TARGET },
  [Blessing.QUEST_PILLAGE]: { target: QUEST_PILLAGE_GOLD_TARGET },
  [Blessing.QUEST_INDECISION]: { target: QUEST_INDECISION_SYNERGIES_TARGET },
  [Blessing.QUEST_CRIT]: { target: QUEST_CRIT_POWER_TARGET, decimals: 1 },
  [Blessing.QUEST_ABSORB]: { target: QUEST_ABSORB_DAMAGE_BLOCKED_TARGET }
}

export const EXPLOIT_DAMAGE_BONUS = 20 // in %
export const LASTING_EFFECTS_BONUS = 40 // in %
export const LASTING_EFFECTS_LUCK = 10

export const PULSE_SHIELD_SPEED_RATIO = 0.5
export const PULSE_SHIELD_ALLY_SPEED = 20
export const MINIMALIST_PP_PER_EMPTY_SLOT = { I: 10, II: 15 } // in % of max PP
export const MINIMALIST_II_NO_ITEM_AP = 40

export const CRITICAL_RUSH_SPEED = { I: 30, II: 50 }
export const CRITICAL_RUSH_DURATION = { I: 8000, II: 12000 }
export const CRITICAL_RUSH_II_STACK_SPEED = 5
// matches REAPER_CLOTH, for abilities that already critically strike
export const CRITICAL_PATH_CRIT_POWER_FALLBACK = 50 // in %
export const CRITICAL_PATH_II_CRIT_CHANCE = 20 // in %

export const LONE_WOLF_SHIELD_RATIO = 0.5
export const LONE_WOLF_SPEED = 80
export const LONE_WOLF_SPEED_DURATION = 5000
export const PARTING_GIFT_ITEMS_REQUIRED = 3
export const PARTING_GIFT_SHIELD = 50
export const REQUIEM_SHIELD_RATIO = 0.15
export const GUARD_FORMATION_SHARE_RATIO = 0.5
export const BRAVE_FORMATION_CRIT_CHANCE_PER_EMPTY_TILE = 10 // in %
export const TOUGH_FORMATION_DEFENSE_PER_ADJACENT_ALLY = 2

export const IMPENDING_DOOM_DELAY = 10000
export const IMPENDING_DOOM_KO_ACCELERATION = 1000

export const STARTER_CHOICE_OPTIONS = 3
export const STARTER_CHOICE_EXTRA_ROUNDS = 8

export const SINGULARITY_OPTIONS = 3
export const SINGULARITY_I_STAGES = [10, 20]
export const SINGULARITY_II_STAGES = [10, 15, 20, 25]

export const CURSOLA_SELL_PRICE = 18

/* the treasure marker is the gold-coin burst rather than the Light spot, so it
   reads as buried loot. Swap the anim key for DIG, PAYDAY or ZYGARDE_CELL to
   try another look; it only needs to be an anim declared in the abilities atlas */
export const TREASURE_TRAIL_HIGHLIGHT_ANIM = "GOLD_RUSH"
export const TREASURE_TRAIL_HIGHLIGHT_ALPHA = 0.55
// half the Light cell's scale of 2, so it sits inside a tile rather than over it
export const TREASURE_TRAIL_HIGHLIGHT_SCALE = 1
export const TRAINING_MONTAGE_TICKET_STAGE_DELAY = 0

/* TEMPLE_OF_LANGUAGE exempts Unown from the board cap. Kept here rather than on
   the Pokemon getter because the exemption depends on the owner, not the unit;
   the pokemon shape is structural so this file stays import-free of models. */
export function countsForTeamSize(
  pokemon: { name: Pkm; doesCountForTeamSize: boolean },
  blessings: Blessing[] | undefined
): boolean {
  if (!pokemon.doesCountForTeamSize) return false
  if (
    blessings?.includes(Blessing.TEMPLE_OF_LANGUAGE) &&
    Unowns.includes(pokemon.name)
  )
    return false
  return true
}

export const BEING_OF_KNOWLEDGE_LEVEL = 7
export const BEING_OF_KNOWLEDGE_MAX_LEVEL = 10

export function getCarouselLockForStage(
  blessings: Blessing[] | undefined,
  stage: number
): { stage: number; guaranteedPick: Pkm } | undefined {
  return blessings
    ?.map((blessing) => BLESSING_CAROUSEL_LOCK[blessing])
    .find((lock) => lock?.stage === stage)
}

/* the Pokemon each hero blessing gifts on pick, and the family whose strongest
   fielded member the blessing then empowers every combat */
export const HERO_BLESSING_GIFT: { [blessing in Blessing]?: Pkm } = {
  [Blessing.OLIVE_GARDEN]: Pkm.DOLLIV,
  [Blessing.ORBITAL_STRIKE]: Pkm.DOTTLER,
  [Blessing.ROOSTING_FLOCK]: Pkm.TRANQUILL,
  [Blessing.SHELL_ARMOR_BLESSING]: Pkm.GROTLE,
  [Blessing.MORTAR_SHELLS]: Pkm.MAGBY,
  [Blessing.ICE_SPEAR]: Pkm.VANILLITE,
  [Blessing.FROST_GEAR]: Pkm.SHELLDER,
  [Blessing.SHUTTLE_BUS]: Pkm.SKIDDO,
  [Blessing.PLUNDER]: Pkm.GALAR_MEOWTH,
  [Blessing.FROST_BURST]: Pkm.SNOVER,
  [Blessing.AURORA_BOREALIS]: Pkm.AMAURA,
  [Blessing.RADIANCE]: Pkm.LARVESTA,
  [Blessing.PACK_ATTACK]: Pkm.HOUNDOUR,
  [Blessing.LEAF_TORNADO]: Pkm.SNIVY,
  [Blessing.MARIACHI_MAYHEM]: Pkm.LOTAD,
  [Blessing.ICEBREAKER]: Pkm.PIPLUP,
  [Blessing.RAMPAGE]: Pkm.DEINO,
  [Blessing.SOUL_DRAIN]: Pkm.LITWICK,
  [Blessing.FLOWER_QUEEN]: Pkm.FLOETTE,
  [Blessing.CHARGING_MY_BUG]: Pkm.GRUBBIN,
  [Blessing.AXE_BLAST]: Pkm.AXEW,
  [Blessing.SNIFFER_DOG]: Pkm.LILLIPUP,
  [Blessing.JESTER]: Pkm.SPRIGATITO,
  [Blessing.TOXIC_RESONANCE]: Pkm.TYMPOLE,
  [Blessing.GRAND_IGNITION]: Pkm.FENNEKIN,
  [Blessing.VALOR]: Pkm.PIGNITE,
  [Blessing.COLONY]: Pkm.SCATTERBUG,
  [Blessing.SAND_BUDDIES]: Pkm.SANDILE
}

export const HERO_BLESSING_FAMILY: { [blessing in Blessing]?: Pkm } = {
  [Blessing.OLIVE_GARDEN]: Pkm.SMOLIV,
  [Blessing.ORBITAL_STRIKE]: Pkm.BLIPBUG,
  [Blessing.ROOSTING_FLOCK]: Pkm.PIDOVE,
  [Blessing.SHELL_ARMOR_BLESSING]: Pkm.TURTWIG,
  [Blessing.MORTAR_SHELLS]: Pkm.MAGBY,
  [Blessing.ICE_SPEAR]: Pkm.VANILLITE,
  [Blessing.FROST_GEAR]: Pkm.SHELLDER,
  [Blessing.SHUTTLE_BUS]: Pkm.SKIDDO,
  [Blessing.PLUNDER]: Pkm.GALAR_MEOWTH,
  [Blessing.FROST_BURST]: Pkm.SNOVER,
  [Blessing.AURORA_BOREALIS]: Pkm.AMAURA,
  [Blessing.RADIANCE]: Pkm.LARVESTA,
  [Blessing.PACK_ATTACK]: Pkm.HOUNDOUR,
  [Blessing.LEAF_TORNADO]: Pkm.SNIVY,
  [Blessing.MARIACHI_MAYHEM]: Pkm.LOTAD,
  [Blessing.ICEBREAKER]: Pkm.PIPLUP,
  [Blessing.RAMPAGE]: Pkm.DEINO,
  [Blessing.SOUL_DRAIN]: Pkm.LITWICK,
  [Blessing.FLOWER_QUEEN]: Pkm.FLABEBE,
  [Blessing.LANCES_ACE]: Pkm.DRATINI,
  [Blessing.CHARGING_MY_BUG]: Pkm.GRUBBIN,
  [Blessing.AXE_BLAST]: Pkm.AXEW,
  [Blessing.SNIFFER_DOG]: Pkm.LILLIPUP,
  [Blessing.JESTER]: Pkm.SPRIGATITO,
  [Blessing.TOXIC_RESONANCE]: Pkm.TYMPOLE,
  [Blessing.GRAND_IGNITION]: Pkm.FENNEKIN,
  [Blessing.VALOR]: Pkm.TEPIG,
  [Blessing.COLONY]: Pkm.SCATTERBUG,
  [Blessing.SAND_BUDDIES]: Pkm.SANDILE
}

/* hero blessings that also relocate the player to a region where their family
   is findable */
export const HERO_BLESSING_MOVES_REGION: Blessing[] = [
  Blessing.ROOSTING_FLOCK,
  Blessing.SHELL_ARMOR_BLESSING,
  Blessing.PLUNDER,
  Blessing.FROST_BURST
]

/* hero blessings that seed the shared pool with their Pokemon, exactly as an
   additional pick would */
export const HERO_BLESSING_ADDS_TO_POOL: Blessing[] = [
  Blessing.FROST_GEAR,
  Blessing.SHUTTLE_BUS,
  Blessing.PLUNDER,
  Blessing.AURORA_BOREALIS,
  Blessing.RADIANCE,
  Blessing.PACK_ATTACK
]

export interface ScheduledBlessingGrant {
  stage: number
  blessing: Blessing
  value?: number
}
